# coding: utf-8

"""
    Courses API

    This API can be used to obtain the information of the courses in the Department of Computer Engineering, University of Peradeniya  # noqa: E501

    OpenAPI spec version: v1
    Contact: e18227@eng.pdn.ac.lk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_course_by_code(self):
        """Test case for get_course_by_code

        """
        pass

    def test_get_course_details_by_semester(self):
        """Test case for get_course_details_by_semester

        """
        pass

    def test_get_courses(self):
        """Test case for get_courses

        """
        pass


if __name__ == '__main__':
    unittest.main()
