# coding: utf-8

# flake8: noqa
"""
    Courses API

    This API can be used to obtain the information of the courses in the Department of Computer Engineering, University of Peradeniya  # noqa: E501

    OpenAPI spec version: v1
    Contact: e18227@eng.pdn.ac.lk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.course import Course
from swagger_client.models.course_list import CourseList
